<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LIN-5CG134B0LH" failures="1" tests="5" name="Personal loan" time="0.065" errors="0" timestamp="2024-03-27T16:49:00 IST">
  <testcase classname="TestNG.Test.Day1" name="Demo" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Test.Day1.Demo(Day1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestNG.Test.Day2" name="ploan" time="0.001"/>
  <testcase classname="TestNG.Test.Day4" name="LoginAPIHomeLoan" time="0.001"/>
  <testcase classname="TestNG.Test.Day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="TestNG.Test.Day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="TestNG.Test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
